#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/nzbget.conf" ]]; then
    log_inf "Installing default [${CONFIG_DIR}/nzbget.conf] file."
    sed -e "s#\\(MainDir=\\).*#\\1${CONFIG_DIR}/downloads#g" \
        -e "s#\\(QueueDir=\\).*#\\1${CONFIG_DIR}/queue#g" \
        -e "s#\\(ScriptDir=\\).*#\\1${CONFIG_DIR}/scripts#g" \
        -e "s#\\(LockFile=\\).*#\\1${CONFIG_DIR}/nzbget.lock#g" \
        -e "s#\\(LogFile=\\).*#\\1${CONFIG_DIR}/nzbget.log#g" \
        -e "s#\\(ShellOverride=\\).*#\\1.py=/usr/bin/python3#g" \
        "${APP_DIR}/bin/nzbget.conf" > "${CONFIG_DIR}/nzbget.conf"
    find "${CONFIG_DIR}/nzbget.conf" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
