#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

# shellcheck disable=SC2086
exec s6-setuidgid hotio "${APP_DIR}/nzbget" --server --option OutputMode=log --configfile "${CONFIG_DIR}/app/nzbget.conf" ${ARGS}
